### ISSUE TITLE
Faire une application serieuse 

### ISSUE THREAD

**Issue by TheNoobProgrammeur** [fferwan/3506_TP3#1]
Tu vas travailler un jour @BastienMarais  ?

**Comment by BastienMarais** [comment]
Travailler mais quelle horreur ! Tu t'ennuis tellement que tu viens faire des issues ici @TheNoobProgrammeur XD ?

**Comment by TheNoobProgrammeur** [comment]
Bah moi j'aurais fait un CI/CD
Franchement obliger les utilisateur a clone ... on est en 2020

**Comment by BastienMarais** [comment]
Je me mettrai au CI/CD lorsque j'aurais des projets plus "funs" et complèxe ^^ pour l'instant ça ne vaut pas le coup.

**Comment by BastienMarais** [comment]
Bref cessons nos bétises.
